name: Configurer Node et Bun
description: Configurer Node.js et Bun pour les flux de travail

inputs:
  node-version:
    description: Version de Node.js
    required: true
  bun-version:
    description: Version de Bun
    required: true
  package-manager-cache:
    description: Transmission au cache du gestionnaire de paquets de actions/setup-node
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Configurer Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        package-manager-cache: ${{ inputs.package-manager-cache }}

    - name: Installer bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}
