packages:
  - packages/**
  - .
  - e2e
  - apps/desktop/src/main

allowBuilds:
  '@lobehub/editor': set this to true or false
  core-js: set this to true or false
  electron: set this to true or false
  es5-ext: set this to true or false
  esbuild: set this to true or false
  ffmpeg-static: set this to true or false
  msgpackr-extract: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false

onlyBuiltDependencies:
  - '@google/genai'
  - '@lobehub/editor'
  - '@vercel/speed-insights'

overrides:
  jose: ^6.1.3
  stylelint-config-clean-order: 7.0.0
  pdfjs-dist: 5.4.530
  react: 19.2.4
  react-dom: 19.2.4
  '@react-pdf/image': 3.0.4
