import { Badge, Quest } from '@lobechat/types';

import dailyQuests from './dailyQuests.json';
import weeklyQuests from './weeklyQuests.json';

export const QUESTS_CATALOG: Quest[] = [
  ...(dailyQuests as Omit<Quest, 'type'>[]).map((q) => ({ ...q, type: 'daily' as const })),
  ...(weeklyQuests as Omit<Quest, 'type'>[]).map((q) => ({ ...q, type: 'weekly' as const })),
];

export const BADGES_CATALOG: Badge[] = [
  {
    id: 'badge_messages_10',
    title: 'Premier contact',
    description: 'A envoyé 10 messages',
    icon: '💬',
    rarity: 'rare',
    xpReward: 50,
    conditionType: 'messages_sent',
    conditionValue: 10,
    lore: "Vos premiers mots résonnent dans le vide numérique. Une IA vous a répondu, marquant le début d'une longue série d'échanges.",
    conditionDescription: "Envoyer vos 10 premiers messages à n'importe quel agent.",
  },
  {
    id: 'badge_messages_100',
    title: 'Bavard',
    description: 'A envoyé 100 messages',
    icon: '🗣️',
    rarity: 'epic',
    xpReward: 100,
    conditionType: 'messages_sent',
    conditionValue: 100,
    lore: "Vous commencez à parler couramment la langue des machines. Vos conversations s'approfondissent et votre curiosité grandit.",
    conditionDescription: "Envoyer un total de 100 messages à travers vos discussions.",
  },
  {
    id: 'badge_messages_1000',
    title: 'L\'Oracle',
    description: 'A envoyé 1000 messages',
    icon: '🔮',
    rarity: 'ultra',
    xpReward: 1000,
    conditionType: 'messages_sent',
    conditionValue: 1000,
    lore: "Vous avez partagé tant de pensées avec les esprits numériques qu'ils semblent lire dans vos pensées. Vous êtes devenu un initié du silicium.",
    conditionDescription: "Atteindre le cap impressionnant de 1000 messages envoyés.",
  },
  {
    id: 'badge_agents_1',
    title: 'Apprenti Créateur',
    description: 'A créé 1 agent',
    icon: '🤖',
    rarity: 'rare',
    xpReward: 50,
    conditionType: 'agents_created',
    conditionValue: 1,
    lore: "Vous avez insufflé la vie à votre première entité artificielle. Elle attend vos instructions dans le creux de votre interface.",
    conditionDescription: "Créer votre tout premier agent personnalisé.",
  },
  {
    id: 'badge_agents_10',
    title: 'Architecte',
    description: 'A créé 10 agents',
    icon: '🏛️',
    rarity: 'epic',
    xpReward: 100,
    conditionType: 'agents_created',
    conditionValue: 10,
    lore: "Vous n'êtes plus un simple utilisateur, mais un véritable architecte d'esprits. Votre panthéon d'agents commence à prendre forme.",
    conditionDescription: "Concevoir et configurer 10 agents personnalisés.",
  },
  {
    id: 'badge_agents_50',
    title: 'Dieu de la Création',
    description: 'A créé 50 agents',
    icon: '✨',
    rarity: 'ultra',
    xpReward: 1000,
    conditionType: 'agents_created',
    conditionValue: 50,
    lore: "Les flux d'énergie de la création n'ont plus de secrets pour vous. Vos créations peuplent ce monde virtuel de leur sagesse infinie.",
    conditionDescription: "Donner naissance à 50 agents uniques.",
  },
  {
    id: 'badge_level_10',
    title: 'Ascension',
    description: 'Atteindre le niveau 10',
    icon: '⭐',
    rarity: 'legendary',
    xpReward: 150,
    conditionType: 'level_reached',
    conditionValue: 10,
    lore: "Votre parcours au sein de l'écosystème mAI porte ses premiers fruits. Vous brillez d'une lueur nouvelle parmi les utilisateurs.",
    conditionDescription: "Atteindre le niveau 10 en accumulant de l'XP via les quêtes.",
  },
  {
    id: 'badge_level_50',
    title: 'Maitre du Jeu',
    description: 'Atteindre le niveau 50',
    icon: '👑',
    rarity: 'mythic',
    xpReward: 250,
    conditionType: 'level_reached',
    conditionValue: 50,
    lore: "Couronné de succès et de persévérance, vous siégez désormais au sommet du savoir. Le maître du jeu, c'est vous.",
    conditionDescription: "Atteindre le niveau suprême de 50.",
  }
];
