import { Badge, Quest } from '@lobechat/types';

export const QUESTS_CATALOG: Quest[] = [
  {
    id: 'daily_message_1',
    title: 'Discuter avec une IA',
    description: 'Envoyer 5 messages à n\'importe quel agent.',
    type: 'daily',
    category: 'message',
    objectiveCount: 5,
    xpReward: 25,
  },
  {
    id: 'daily_agent_1',
    title: 'Créateur en herbe',
    description: 'Créer un nouvel agent personnalisé.',
    type: 'daily',
    category: 'agent',
    objectiveCount: 1,
    xpReward: 25,
  },
  {
    id: 'daily_task_1',
    title: 'Planificateur',
    description: 'Créer 2 nouvelles tâches.',
    type: 'daily',
    category: 'task',
    objectiveCount: 2,
    xpReward: 25,
  },
  {
    id: 'daily_legendary_1',
    title: 'Grand orateur',
    description: 'Envoyer 50 messages en une journée.',
    type: 'daily',
    category: 'message',
    objectiveCount: 50,
    xpReward: 150,
    isLegendary: true,
  },
  {
    id: 'weekly_message_1',
    title: 'Conversations intenses',
    description: 'Envoyer 100 messages dans la semaine.',
    type: 'weekly',
    category: 'message',
    objectiveCount: 100,
    xpReward: 25,
  },
  {
    id: 'weekly_agent_1',
    title: 'Assemblage',
    description: 'Créer 3 agents personnalisés.',
    type: 'weekly',
    category: 'agent',
    objectiveCount: 3,
    xpReward: 25,
  },
  {
    id: 'weekly_legendary_1',
    title: 'Dévouement hebdomadaire',
    description: 'Compléter 15 quêtes quotidiennes.',
    type: 'weekly',
    category: 'mixed',
    objectiveCount: 15,
    xpReward: 150,
    isLegendary: true,
  },
  {
    id: 'daily_message_night',
    title: 'Oiseau de nuit 🦉',
    description: 'Envoyez un message entre minuit et 4h du matin',
    type: 'daily',
    category: 'message',
    objectiveCount: 1,
    xpReward: 50,
    isHidden: true,
  },
  {
    id: 'daily_message_gpt4',
    title: 'Fidèle au poste 🤖',
    description: 'Utilisez un modèle de la famille GPT-4 aujourd\'hui',
    type: 'daily',
    category: 'message',
    objectiveCount: 1,
    xpReward: 40,
    isHidden: true,
  }
];

export const BADGES_CATALOG: Badge[] = [
  {
    id: 'badge_messages_10',
    title: 'Premier contact',
    description: 'A envoyé 10 messages',
    icon: '💬',
    rarity: 'rare',
    xpReward: 50,
    conditionType: 'messages_sent',
    conditionValue: 10,
  },
  {
    id: 'badge_messages_100',
    title: 'Bavard',
    description: 'A envoyé 100 messages',
    icon: '🗣️',
    rarity: 'epic',
    xpReward: 100,
    conditionType: 'messages_sent',
    conditionValue: 100,
  },
  {
    id: 'badge_messages_1000',
    title: 'L\'Oracle',
    description: 'A envoyé 1000 messages',
    icon: '🔮',
    rarity: 'ultra',
    xpReward: 1000,
    conditionType: 'messages_sent',
    conditionValue: 1000,
  },
  {
    id: 'badge_agents_1',
    title: 'Apprenti Créateur',
    description: 'A créé 1 agent',
    icon: '🤖',
    rarity: 'rare',
    xpReward: 50,
    conditionType: 'agents_created',
    conditionValue: 1,
  },
  {
    id: 'badge_agents_10',
    title: 'Architecte',
    description: 'A créé 10 agents',
    icon: '🏛️',
    rarity: 'epic',
    xpReward: 100,
    conditionType: 'agents_created',
    conditionValue: 10,
  },
  {
    id: 'badge_agents_50',
    title: 'Dieu de la Création',
    description: 'A créé 50 agents',
    icon: '✨',
    rarity: 'ultra',
    xpReward: 1000,
    conditionType: 'agents_created',
    conditionValue: 50,
  },
  {
    id: 'badge_level_10',
    title: 'Ascension',
    description: 'Atteindre le niveau 10',
    icon: '⭐',
    rarity: 'legendary',
    xpReward: 150,
    conditionType: 'level_reached',
    conditionValue: 10,
  },
  {
    id: 'badge_level_50',
    title: 'Maitre du Jeu',
    description: 'Atteindre le niveau 50',
    icon: '👑',
    rarity: 'mythic',
    xpReward: 250,
    conditionType: 'level_reached',
    conditionValue: 50,
  }
];
