name: Configurer Node et pnpm
description: Configurer Node.js et pnpm pour les flux de travail

inputs:
  node-version:
    description: Version de Node.js
    required: true
  package-manager-cache:
    description: Transmission au cache du gestionnaire de paquets de actions/setup-node
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Installer pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Configurer Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        package-manager-cache: ${{ inputs.package-manager-cache }}
