name: 🔀 Création Automatique de PR

on:
  push:
    branches-ignore:
      - 'canary'
      - 'main'
      - 'master'

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: 🚀 Création ou Mise à jour de la PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          TEMPLATE_PATH=".github/PULL_REQUEST_TEMPLATE.md"
          
          if [ ! -f "$TEMPLATE_PATH" ]; then
            echo "❌ Erreur : Le fichier $TEMPLATE_PATH n'existe pas !"
            exit 1
          fi

          COMMIT_MSG="$HEAD_COMMIT_MESSAGE"
          BRANCH_NAME="$REF_NAME"

          # On vérifie si une PR existe déjà pour cette branche pour éviter les doublons
          PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number')

          if [ -n "$PR_NUMBER" ]; then
            echo "🔄 La PR #$PR_NUMBER existe déjà. Aucune action requise."
          else
            echo "🆕 Aucune PR trouvée. Création d'une nouvelle PR..."
            gh pr create \
              --title "$COMMIT_MSG" \
              --body-file "$TEMPLATE_PATH" \
              --head "$BRANCH_NAME" \
              --base main
          fi