name: 🚀 Deploy to Vercel via GitHub Actions

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches:
      - canary
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  Deploy-Production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/canary'
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout du code
        uses: actions/checkout@v4

      - name: 🧹 Nettoyer le dossier .vercel résiduel
        run: rm -rf .vercel

      - name: 🛠️ Setup Environment (Node.js, pnpm & Bun)
        uses: ./.github/actions/setup-env
        with:
          node-version: 20

      - name: ⚡ Install Vercel CLI
        run: npm install --global vercel@latest

      - name: 📥 Installation des dépendances
        run: pnpm install

      - name: 🏗️ Build Project Artifacts
        env:
          KEY_VAULTS_SECRET: ${{ env.KEY_VAULTS_SECRET }}
        run: vercel build --prod --token=${{ env.VERCEL_TOKEN }}

      - name: 🌐 Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --archive=tgz --prod --token=${{ env.VERCEL_TOKEN }}

  Deploy-Preview:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref != 'refs/heads/canary')
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout du code
        uses: actions/checkout@v4

      - name: 🧹 Nettoyer le dossier .vercel résiduel
        run: rm -rf .vercel

      - name: 🛠️ Setup Environment (Node.js, pnpm & Bun)
        uses: ./.github/actions/setup-env
        with:
          node-version: 20

      - name: ⚡ Install Vercel CLI
        run: npm install --global vercel@latest

      - name: 📥 Installation des dépendances
        run: pnpm install

      - name: 🏗️ Build Project Artifacts
        env:
          KEY_VAULTS_SECRET: ${{ env.KEY_VAULTS_SECRET }}
        run: vercel build --token=${{ env.VERCEL_TOKEN }}

      - name: 🌐 Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --archive=tgz --token=${{ env.VERCEL_TOKEN }}