name: 🐛 lint-command

on:
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      quiet:
        description: 'Activer le mode silencieux (--quiet)'
        required: false
        type: boolean
        default: true
      lint:
        description: 'Quel linter exécuter ?'
        required: false
        type: choice
        options:
          - eslint
          - prettier
          - stylelint
          - all
        default: 'eslint'

jobs:
  eslint:
    name: 🐛 ESLint
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout du code
        uses: actions/checkout@v4

      - name: 🛠️ Setup Environment
        uses: ./.github/actions/setup-env

      - name: 💾 Obtenir le chemin du cache pnpm
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: 📦 Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 📥 Installation des dépendances
        run: pnpm install

      - name: 🐛 Exécution du Linter
        continue-on-error: true
        run: |
          LINT_TARGET="${{ github.event.inputs.lint || 'eslint' }}"
          QUIET_FLAG="${{ github.event.inputs.quiet }}"
          
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            QUIET_FLAG="true"
          fi

          QUIET_ARG=""
          if [ "$QUIET_FLAG" == "true" ]; then
            QUIET_ARG="--quiet"
          fi

          run_eslint() {
            echo "Exécution de ESLint..."
            pnpx eslint . --fix $QUIET_ARG
          }

          run_prettier() {
            echo "Exécution de Prettier..."
            pnpx prettier -c --write "**/**"
          }

          run_stylelint() {
            echo "Exécution de Stylelint..."
            pnpx stylelint "src/**/*.{js,jsx,ts,tsx}" --fix $QUIET_ARG
          }

          if [ "$LINT_TARGET" == "eslint" ]; then
            run_eslint
          elif [ "$LINT_TARGET" == "prettier" ]; then
            run_prettier
          elif [ "$LINT_TARGET" == "stylelint" ]; then
            run_stylelint
          elif [ "$LINT_TARGET" == "all" ]; then
            run_eslint
            run_prettier
            run_stylelint
          fi
